#pragma once

const char* character_anim_1() {
    return
        R"(
<?xml version="1.0"?>
<data>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/front/enemy1_front_walk1.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/left/enemy1_left_walk1.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/right/enemy1_right_walk1.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/back/enemy1_back_walk1.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/front/enemy1_front_walk1.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/front/enemy1_front_walk2.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/front/enemy1_front_walk3.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/front/enemy1_front_walk4.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/left/enemy1_left_walk1.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/left/enemy1_left_walk2.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/left/enemy1_left_walk3.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/left/enemy1_left_walk4.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/right/enemy1_right_walk1.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/right/enemy1_right_walk2.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/right/enemy1_right_walk3.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/right/enemy1_right_walk4.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/back/enemy1_back_walk1.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/back/enemy1_back_walk2.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/back/enemy1_back_walk3.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/walk/back/enemy1_back_walk4.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/scythe/front/dotchara1_ver3_front_scythe1.png</filename>
            <duration>250</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/scythe/front/dotchara1_ver3_front_scythe4.png</filename>
            <duration>50</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/scythe/front/dotchara1_ver3_front_scythe5.png</filename>
            <duration>250</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/scythe/left/dotchara1_ver3_left_scythe1.png</filename>
            <duration>250</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/scythe/left/dotchara1_ver3_left_scythe4.png</filename>
            <duration>50</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/scythe/left/dotchara1_ver3_left_scythe5.png</filename>
            <duration>250</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/scythe/right/dotchara1_ver3_right_scythe1.png</filename>
            <duration>250</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/scythe/right/dotchara1_ver3_right_scythe4.png</filename>
            <duration>50</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/scythe/right/dotchara1_ver3_right_scythe5.png</filename>
            <duration>250</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/scythe/back/dotchara1_ver3_back_scythe1.png</filename>
            <duration>250</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/scythe/back/dotchara1_ver3_back_scythe4.png</filename>
            <duration>50</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/scythe/back/dotchara1_ver3_back_scythe5.png</filename>
            <duration>250</duration>
        </frame>
    </animation>
</data>
)";
}
